global using System.Data;
global using SFCTOFC.DailySalesPlanManagementApplication.Common.Interfaces;
global using SFCTOFC.DailySalesPlanManagementApplication.Common.Models;
global using SFCTOFC.DailySalesPlanManagementApplication.Common.Extensions;
global using SFCTOFC.DailySalesPlanManagementDomain.Entities;
global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using Microsoft.EntityFrameworkCore;
